---
# tasks file for vim
#

- name: Ensure vim directories exist
  file:
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - autoload
    - bundle
    - plugin
    - ftplugin

- name: Install pathogen
  get_url:
    url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload"
    mode: 0644
  register: result

- name: Copy local pathogen if downloading fails
  copy:
    src: autoload/pathogen.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload"
    mode: 0644
  when: result|failed

- name: Copy autoload files
  copy:
    src: "autoload/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.vim/autoload"
    mode: 0644
  with_items:
    - csapprox.vim

- name: Copy filetype plugin files
  copy:
    src: "ftplugin/"
    dest: "{{ ansible_env.HOME }}/.vim/ftplugin"
    mode: 0644

- name: Install syntastic
  git:
    repo: https://github.com/scrooloose/syntastic.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/syntastic"

- name: Install colors
  unarchive:
    src: colors.tar.gz
    dest: "{{ ansible_env.HOME }}/.vim"
  creates: "{{ ansible_env.home }}/.vim/colors"

- name: Install .vimrc
  copy:
    src: ".vimrc"
    dest: "{{ ansible_env.HOME }}"
    mode: 0644
